name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        sphinx-version: ["3.*", "4.*", "5.*"]
        include:
          - {python-version: "3.6", sphinx-version: "1.8"}
          - {python-version: "3.7", sphinx-version: "2.0"}
          #- {python-version: "3.10", sphinx-version: "5.*"}
        exclude:
          - {python-version: "3.10", sphinx-version: "3.*"}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx==${{ matrix.sphinx-version }}
        pip install .[test]
        case "${{ matrix.sphinx-version }}" in
        3* | 2* | 1*)
            pip install 'jinja2<3.1'
            ;;
        esac
    - name: List dependencies
      run: |
        pip list
    #- name: Install sphinx ${{ matrix.sphinx-version }}
    #  run: |
    #    pip install sphinx==${{ matrix.sphinx-version }}
    - name: Test
      run: |
        bash tests/test.sh
